server:
  port: 5555
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://10.123.3.228:3000"
              - "http://localhost:3000"
              - "http://localhost:3000/tsm"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - PUT
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8189/
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/ttsystem-core
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8721/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/ttsystem-auth
            - JwtAuthFilter

jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g