server:
  port: 5555
  servlet:
    context-path: /gateway-service
managment:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway-service
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://10.123.3.228:3000"
              - "http://localhost:3000"
              - "http://localhost:3000/tsm"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - PUT
            allowedHeaders: "*"
      routes:
        - id: core-service-id
          uri: lb://core-service/core
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/ttsystem-core
            - JwtAuthFilter
        - id: auth-service-id-1
          uri: lb://auth-service/auth
          predicates:
            - Path=/auth/api/v1/auth
          filters:
            - StripPrefix=1
            - PrefixPath=/ttsystem-auth
        - id: auth-service-id-2
            uri: lb://auth-service/auth
            predicates:
              - Path=/auth/api/v1/registration
            filters:
              - StripPrefix=1
              - PrefixPath=/ttsystem-auth
        - id: auth-service-id-3
            uri: lb://auth-service/auth
            predicates:
              - Path=/auth/api/v1/users/**
            filters:
              - StripPrefix=1
              - PrefixPath=/ttsystem-auth
              - JwtAuthFilter
        - id: front-service-id
          uri: http://localhost:3000/tsm
          predicates:
            - Path=/tsm/**
          filters:
            - StripPrefix=1
            - PrefixPath=/ttsystem-front
eureka:
  client:
    serviceUrl:
      defaultZone: http://kvakozaBrus836233:leruIOOO89637@localhost:8010/eureka
  instance:
    preferIpAddress: true

jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g