server:
  port: 8010
spring:
  security:
    basic:
      enabled: true
    user:
      name: kvakozaBrus836233
      password: leruIOOO89637
  cloud:
    inetutils:
      ignored-interfaces:
        # You can use wildcards as well

  application:
    name: eureka-server
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    preferIpAddress: true
logging:
  level:
    org.springframework.cloud.commons.util.InetUtils: trace
