server:
  port: 8189
  servlet:
    context-path: /ttsystem-core
utils:
  cart:
    prefix: TTSystem
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./orders;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
integrations:
  auth-service:
    url: http://localhost:5555/auth/api/v1/
    connect-timeout: 2000
    read-timeout: 10000
    write-timeout: 2000

