server:
  port: 0
  servlet:
    context-path: /ttsystem-core
utils:
  cart:
    prefix: TTSystem
spring:
  application:
    name: core-service
  cloud:
      gateway:
        discovery:
          locator:
            enabled: true
            lowerCaseServiceId: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./tasks;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
integrations:
  auth-service:
    url: http://AUTH-SERVICE/ttsystem-auth/
    connect-timeout: 2000
    read-timeout: 10000
    write-timeout: 2000
interval:
  closingTimePoints: 3600000
eureka:
  client:
    serviceUrl:
      defaultZone: http://kvakozaBrus836233:leruIOOO89637@localhost:8010/eureka
  instance:
    preferIpAddress: true
